config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :sessions
  resources :products
  resources :transactions
end

app/models/product.rb
class Product < ActiveRecord::Base
		belongs_to :user
		# has_one :transaction
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :buyer, :class_name => 'User'
  belongs_to :seller, :class_name => 'User'
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :products
	has_many :sales, :class_name => 'Transaction', :foreign_key => 'seller_id'
	has_many :purchases, :class_name => 'Transaction', :foreign_key => 'buyer_id'
	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
	validates :name, :email, presence: true
	validates :email, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def require_login
    redirect_to '/sessions/new' if session[:user_id] == nil
  end

  def require_correct_user
    user = User.find(params[:id])
    redirect_to "/users/#{current_user.id}" if current_user != user
  end
  
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		if session[:user_id]
			@user = User.find(session[:user_id])
			if Transaction.pluck(:product_id) == []
					@products = Product.all
			else
				@products = Product.where('id not in (?)',Transaction.pluck(:product_id))
			end
		end
	end

	def create
		p = product_params
		p['user'] = User.find(session[:user_id])
		product = Product.create(p)
		redirect_to :back
	end

	def destroy
		Product.delete(params[:id])
		redirect_to :back
	end


	def product_params
    params.require(:product).permit(:name, :amount)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by(:email => user_params[:email])
		if user
			if  user.authenticate(user_params[:password])
				session[:user_id] = user.id 
				redirect_to user_path(session[:user_id])
			else
				flash[:errors] = ["Invalid password"]
				redirect_to :back
			end
		else
			flash[:errors] = ["User not found"]
			redirect_to :back
		end 
	end 

	def destroy
		session.clear
		redirect_to "/"
	end

	private

	def user_params
		params.require(:user).permit(:email, :password)
	end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	def create
		# puts params[:seller], params[:product]
		Transaction.create(
			buyer: User.find(session[:user_id]),
			seller:User.find(params[:seller]),
			product: Product.find(params[:product]))
		redirect_to :back
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		user = User.create(user_params)
		if user.errors.full_messages.length !=0 
			flash[:errors] = user.errors.full_messages 
			redirect_to :back
		else 
			session[:user_id] = user.id
			redirect_to user_path(session[:user_id])
		end
	end

	def show
		if session[:user_id]
			@user = User.find(params[:id])
			if Transaction.pluck(:product_id) == []
					@userProducts = @user.products.all
			else
				@userProducts = @user.products.where('id not in (?)',Transaction.pluck(:product_id))
			end
			@sales = @user.sales
			@purchases = @user.purchases
			render 'dashboard'
		else 
			redirect_to "/"
		end
	end


	private

	def user_params
    params.require(:user).permit(:name,:email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:errors] %>
  <% flash[:errors].each do |e| %>
    <p><%= e %></p>
  <% end %>
<% end %>

<%= yield %>
</body>
</html>

app/views/products/index.html.erb
<div id="container">
<div id="header">		
	<h1>Hi <%= @user.name %></h1>
	<%= link_to 'Log Out', session_path("user_id"), :method => :delete %>
	<a href="<%=user_path(@user.id)%>">Go to dashboard</a>
</div>


<table class='table'>
	<tr>
		<th>Product </th>
		<th>Seller </th>
		<th>Date Posted</th>
		<th>Amount</th>
		<th>Action</th>
	</tr>

	<% if @products%>
		<% @products.each do |product|%>
		<tr>
			<td><%= product.name %></td>
			<td><%= product.user.name%></td>
			<td><%= product.created_at.strftime('%B %d, %Y')   %></td>
			<td><%= product.amount %></td>
			<% if product.user.id != session[:user_id]%>
				<td><%= link_to 'Buy', transactions_path(:seller => product.user.id , :product => product.id), method: :post %></td>
				<%else%>
				<td></td>
			<%end%>
		<% end %>
	<% end %>

	</div>

app/views/users/dashboard.html.erb
<div id="container">
<div id="header">		
	<h1>Hi <%= @user.name %></h1>
	<%= link_to 'Log Out', session_path("user_id"), :method => :delete %>
	<a href="<%= products_path %>">Go to All products</a>

</div>
	
	<form action='<%= products_path %>' method='post' class="box">
		<h3>Sell Product</h3>
		<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
		<label>Name : <input type="text" name="product[name]"></label>
		<label>Amount : <input <input type="number" step="0.01" name="product[amount]"></label>	
		<label><input type='submit' value='Sell' class='green'></label>
	</form>
	<div id="tables">
		<h3>Your products that are not sold yet</h3>
		<table class='table'>
			<tr>
				<th>Product </th>
				<th>Date Poted</th>
				<th>Amount</th>
				<th>Action</th>
			</tr>

			<% if @userProducts%>
				<% @userProducts.each do |product|%>
				<tr>
					<td><%= product.name %></td>
					<td><%= product.created_at.strftime('%B %d, %Y')   %></td>
					<td><%= product.amount %></td>
					<td><%= link_to 'Remove', product_path(product.id), :method => :delete %></td>
				<% end %>
			<% end %>
			</tr>
		</table>

		<h3>Sales</h3>
		<table class='table'>
			<tr>
				<th>Product </th>
				<th>Date Poted</th>
				<th>Buyer</th>
				<th>Amount</th>
			</tr>
			
			<% if @sales%>
				<% @sales.each do |transaction|%>
				<tr>
					<td><%= transaction.product.name %></td>
					<td><%= transaction.created_at.strftime('%B %d, %Y')   %></td>
					<td><%= transaction.buyer.name %></td>
					<td><%= transaction.product.amount %></td>
				<% end %>
			<% end %>
			</tr>
		</table>


		<h3>Purchases</h3>
		<table class='table'>
			<tr>
				<th>Product </th>
				<th>Date Posted</th>
				<th>Seller</th>
				<th>Amount</th>
			</tr>
			
			<% if @purchases%>
				<% @purchases.each do |transaction|%>
				<tr>
					<td><%= transaction.product.name %></td>
					<td><%= transaction.created_at.strftime('%B %d, %Y')   %></td>
					<td><%= transaction.seller.name %></td>
					<td><%= transaction.product.amount %></td>
				<% end %>
			<% end %>
			</tr>
		</table>
	</div>
</div>

app/views/users/index.html.erb
<div id="container">
	<div id="header">
		<h2 class="inline">Welcome!</h2>          
	</div>
	<div id="mid">
		<div id="registration" class="box">
			<h1>Register</h1>

			<form action="<%= users_path %>" method="post">
				<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
				<label>Name: <input type="text" name="user[name]"></label>
				<label>Email: <input type="email" name="user[email]"></label>
				<label>Password:<input type="password" name="user[password]"></label>
				<label><input class="green" type="submit" name="submit" value="Register"></label>
			</form>
	</div>
		
	<div id="login" class="box">
		<h1>Login</h1>
		<form action="<%= sessions_path%>" method="post">
			<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
			<label>Email: <input type="email" name="user[email]"></label>
			<label>Password:<input type="password" name="user[password]"></label>
			<label><input class="green"  type="submit" name="submit" value="Login"></label>
		</form>
	</div>

	</div>
</div>